### ISSUE TITLE
Missing python 3.11 in build.sh

### ISSUE THREAD

**Issue by alexlopezc** [osmcode/pyosmium-wheel-build#18]
Hello!

The wheel for python 3.11 is not being built/published and it forces us to require compile tools for installing it from sources when upgrading to last version.

It may be only a matter of adding the version to build.sh since the pyosmium repository is already building it through GitHub Actions, but I am not 100% sure multibuild is supporting it yet.

Many thanks!

**Comment by lonvia** [comment]
I'm quite aware. Official support for Python 3.11. has arrived on the pyosmium master branch only after the last release. Binary wheels for Python 3.11 will be supported starting with the next release. There is no ETA for the next release.

**Comment by alexlopezc** [comment]
Thank you for the fast response. No hurry at all.

**Comment by lonvia** [comment]
There is now a 3.11 wheel build available in a pre-release version. Install with `pip install --pre osmium`

**Comment by alexlopezc** [comment]
Amazing! Thank you!
