### ISSUE TITLE
Windows wheels

### ISSUE THREAD

**Issue by jman005** [osmcode/pyosmium-wheel-build#3]
Would still really like to use pyosmium on Windows. Are windows wheels planned to be built?

**Comment by lonvia** [comment]
We already provide wheels for 64bit Windows via pip install.

**Comment by jman005** [comment]
They don't seem to function - using pip install on Windows 10 x64, Python 3.5.2 attempts to find the required dependencies for building and fails. I'll try to manually grab and install the Windows wheel from PyPI later and see if it's working correctly.

**Comment by lonvia** [comment]
You need Python 2.7, 3.6 or 3.7.

**Comment by jman005** [comment]
I see, closing.
